version : "3"
 services:
  nginx:
		container_name: nginx
	 	image: nginx
		pull_policy: never
		build: ./requirments/nginx
		port:
			- "443:443"
		networks:
			- inception
		volumes:
	  	- wp-volume:/var/ww/
		restart: always
	
	mariadb:
		container_name: mariadb
		image: mariadb
		pull_policy: never
		build: ./requirments/mariadb
		env_file:
			- .env
		networks:
	  	- inception
		volumes:
	  	- db-volume:/var/lib/mysql
  	restart: always
  
	wordpress:
		container_name: wordpress
		image: wordpress
		pull_policy: never
		build: ./requirements/wordpress
		depends_on:
			- mariadb
		env_file:
			- .env
		networks:
			- inception
		volumes:
			- wp-volume:/var/www/html
		restart: always

volumes:
	db-volume:
		driver: local
		driver_opts:
			device: /home/suhwpark/data/db-data
			type: none
			o: bind
	wordpress-volume:
		driver: local
		driver_opts:
			device: /home/suhwpark/data/wp-data
			type: none
			o: bind

networks:
	inception:
		driver: bridge